#pragma once

#include "kaizermud/base.h"
#include <ctime>
#include <string>
#include <map>
#include <unordered_map>
#include <vector>
#include <memory>
#include <list>
#include <boost/json.hpp>
#include <optional>
#include <boost/asio/experimental/channel.hpp>
#include <boost/system.hpp>
#include <boost/asio/error.hpp>

namespace kaizermud::net {

    enum Protocol : uint8_t {
        Telnet = 0,
        WebSocket = 1
    };

    enum ColorType : uint8_t {
        NoColor = 0,
        Standard = 1,
        Xterm256 = 2,
        TrueColor = 3
    };

    struct ProtocolCapabilities {
        Protocol protocol{Telnet};
        bool encryption = false;
        std::string clientName = "UNKNOWN", clientVersion = "UNKNOWN";
        std::string encoding = "";
        bool utf8 = false;
        ColorType colorType = NoColor;
        int width = 80, height = 52;
        bool gmcp = false, msdp = false, mssp = false, mxp = false;
        bool mccp2 = false, mccp2_active = false, mccp3 = false, mccp3_active = false;
        bool ttype = false, naws = true, sga = true, linemode = false;
        bool force_endline = false, oob = false, tls = false;
        bool screen_reader = false, mouse_tracking = false, vt100 = false;
        bool osc_color_palette = false, proxy = false, mnes = false;
        void deserialize(const boost::json::value &j);
    };

    class ClientConnection {
    public:
        using Channel = boost::asio::experimental::channel<void(boost::system::error_code, boost::json::value)>;
        ClientConnection(uint64_t conn_id, Channel chan);
        // Some time structs to handle when we received connections.
        // These probably need some updating on this and Thermite side...
        time_t connected{};
        time_t last_activity{};
        time_t last_read{};

        // This is embedded for ease of segmentation but this struct isn't
        // actually used anywhere else.
        ProtocolCapabilities capabilities;

        // The connection ID is a unique identifier for this connection.
        // It is generated by Thermite. Thermite should never re-use IDs
        // so if we ever get sent a duplicate by Thermite, something is
        // terribly wrong.
        uint64_t conn_id{};

        // A Connection might or might not be logged in. -1 means not.
        // Still debating using uint64_t for IDs and having std::optional<uint64_t>
        // represent an unset or invalid ID. But a lot of softtware, like sqlite doesn't
        // differentiate between signed and unsigned, so maybe staying signed is best.
        int64_t account_id{-1};

        // Later we'll need to handle more than just text commands. But this should handle
        std::list<std::string> pending_commands;

        // Some basic methods I need to implement.
        void sendText(const std::string &messg);
        void sendLine(const std::string &messg);
        void sendMSSP(const std::vector<std::tuple<std::string, std::string>> &data);
        void sendGMCP(const std::string &txt);

        Channel fromLink;

    };

    extern std::unordered_map<uint64_t, std::shared_ptr<ClientConnection>> connections;
}